### PR TITLE
Release PR charms to Charmhub branch

### PR DESCRIPTION
**Pull request by carlcsaposs-canonical**

### CODE REVIEW

**Comment by paulomach** [comment]
> > This will create a branch for every single PR. Why not just do it manually when necessary?
> 
> I didn't see any harm in creating a branch for each PR, so I thought it would be more convenient to automate it
> 
> Also I thought it might make debugging easier, since you wouldn't need to re-trigger CI to upload the *.charm file
> 
> Happy to close this PR if it's not helpful

Tbf, there's no big drawback since branches expires in 30 days. I'd like to see @taurus-forever opinion

**Comment by taurus-forever** [comment]
It is absolutely necessary functionality, but must be controller by author.
Producing charm branches for every PR not necessary (performance and garbage).

What about to create charmhub `branch` if PR has a special "label"?
e.g. Git/PR branch is "ppa/<whatever>" => charm branch "8.0/edge/ppa-whatever".  For example it will allow to map (in the future) PPA in SNAP with PPA in charm. At some point you might want to inclide PPA of mysql/mysql-router in mysql-bundle so you need cross-repos and cross-PRs PPA labeling.

P.S. thank you for pushing this forward. Let's sync 1:1 about my vision here. I was planning to discover this direction after the Prague, but good to have it now too!

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical new proposal: Let's publish charmhub branch after Data Team member comment `/publish` with bot reply: `juju deploy mysql --channel 8.0/edge/pr199` ?

Like juju does with [/merge](https://github.com/juju/juju/pull/17367#issuecomment-2109254012).

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical releasing charmhub branch on the every PR (commit to PR) is not an option.
Do you have other proposals here?

**Comment by taurus-forever** [comment]
@taurus-forever what would need to happen for that to be an option?

Possibility to remove secrets/private code/license vialation/... from public access.
Each revision on charmhub stays forever there, e.g. pgbouncer rev 158 cleaned:

image

but still can be deployed:
```
ubuntu@juju342:~$ juju deploy pgbouncer --channel 1/stable --revision 158
Deployed "pgbouncer" from charm-hub charm "pgbouncer", revision 158 in channel 1/stable on ubuntu@22.04/stable
```

**Comment by taurus-forever** [comment]
I believe it is a design decision which cannot be (easily) changed. You can request it if you want... 2026?
I wish to use charmhub branches. IMHO, comment `/publish` or GH label is only a way to use this feature.

**Comment by paulomach** [comment]
Closing to avoid big jumps on charm revisions

**Comment by taurus-forever** [comment]
:sob:

**Pull request closed without merging**
