### PR TITLE
DPE-5540 Skip plugin install for not file found

### PR DESCRIPTION
**Pull request by paulomach**
## Issue

1. `config_change` hook will try to install plugins if configuration diff so indicates, even if plugins files are not available.
2. admin address enabled charms revisions will fail to connect to mysqld case it's not restarted

Case:
  `refresh` ran without `pre-upgrade-check` - so snap is not updated (no plugin files) but config changed is triggered.

## Solution
1. Check for plugin file before try install. Skip if file not found
2. Ensure mysqld restarts on post refresh `config_change` event

### CODE REVIEW

**Review by shayancanonical — COMMENTED** [review]
looks good. still confused about the symptoms of the issue - if the charm would enter an error state previously, i would recommend adding a test that runs upgrade without `pre-upgrade-check` to ensure that things start up normally. thoughts?

**Review by taurus-forever — APPROVED** [review]
LGTM here, ACK to Shayan: adding a test to run refresh without pre-upgrade-check will help us returning here for the following candidate revisions.

**Comment by taurus-forever** [comment]
> ... if the charm would enter an error state previously...

Yes, see https://warthogs.atlassian.net/browse/DPE-5540

**Comment by paulomach** [comment]
> looks good. still confused about the symptoms of the issue - if the charm would enter an error state previously, i would recommend adding a test that runs upgrade without `pre-upgrade-check` to ensure that things start up normally. thoughts?

You are right. I will include a test before merge

**Pull request merged**
