### PR TITLE
Bump cffi to version 1.16.0

### PR DESCRIPTION
**Pull request by sinclert-canonical**
This PR updates the `cffi` package to use version 1.16.0. This is not the newest version os such package, but it is the closest to the one we are already using that supports Python 3.12. All other packages within the [poetry.lock](https://github.com/canonical/mysql-operator/blob/70ba5f907cbf78c66561b37b5bf01cc90c0c4992/poetry.lock) file support this version of Python already (search for `cp312`).

Without this change, Python 3.12 cannot be used for local development.

### CODE REVIEW

**Comment by taurus-forever** [comment]
Up 2 @paulomach and @carlcsaposs-canonical here.

**Comment by sinclert-canonical** [comment]
For context, all the other MySQL repos are using at least version 1.16.0. See:

- [mysql-bundle](https://github.com/canonical/mysql-bundle/blob/8bd74f6331248aa171adfcdbd0e4861631d58886/poetry.lock#L174-L248).
- [mysql-k8s-operator](https://github.com/canonical/mysql-k8s-operator/blob/30dd0d4a16db7bb61cd511784ad9a162b988efb2/poetry.lock#L223-L282).
- [mysql-k8s-bundle](https://github.com/canonical/mysql-k8s-bundle/blob/485a7542de7efa79264225faf0f5fb137e94e270/poetry.lock#L174-L248).
- [mysql-router-operator](https://github.com/canonical/mysql-router-operator/blob/60ad0549c590d48d77d37f83fe8d105f5a182d4a/poetry.lock#L135-L194).
- [mysql-router-k8s-operator](https://github.com/canonical/mysql-router-k8s-operator/blob/d94843fd840f0dc43cda074e57851b483a165614/poetry.lock#L196-L255).

**Comment by taurus-forever** [comment]
OK, the reason why this is lacking behind is[ lack of love to renovate on this repo](https://github.com/canonical/mysql-operator/pull/425/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89L217).
@paulomach please chek and restore renovate OR reviews here, please.

**Review by taurus-forever — APPROVED** [review]

**Comment by paulomach** [comment]
> OK, the reason why this is lacking behind is[ lack of love to renovate on this repo](https://github.com/canonical/mysql-operator/pull/425/files#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89L217). @paulomach please chek and restore renovate OR reviews here, please.

Reviews incoming. I'm committed to increase my love with renovate

**Review by paulomach — APPROVED** [review]

**Pull request merged**
